### ISSUE TITLE
3dfier says "Config file is valid" but get yaml-cpp error

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/3dfier#36]
On v0.9.7 when running with the config below, I get the following error:

```
Reading config file: mytestarea_config.yml
Config file is valid.
terminate called after throwing an instance of 'YAML::TypedBadConversion<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >'
  what():  yaml-cpp: error at line 0, column 0: bad conversion
Aborted
```

I noticed that it is due to the empty `input_polygons: height_field: ` argument. When I delete or comment out the argument, 3dfier runs without error. 

mytestarea_config.yml
```
input_polygons:
  - datasets: 
      - /example_data/t_25gn1_c2.sqlite
    uniqueid: identificatie
    lifting: Building
    height_field: 

lifting_options: 
  Building:
    height_roof: percentile-90
    height_floor: percentile-10
    lod: 1

input_elevation:
  - datasets:
      - /example_data/c_25gn1_b.laz
    omit_LAS_classes:
      - 1 
    thinning: 0

options:
  building_radius_vertex_elevation: 3.0
  radius_vertex_elevation: 1.0
  threshold_jump_edges: 0.5

output: 
  format: OBJ
  building_floor: false
  vertical_exaggeration: 0
```
