### ISSUE TITLE
OBJ output with missing walls and floor

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/3dfier#42]
I've just compiled 3dfier from the master branch and trying to generate an OBJ model but for a couple of buildings the walls are not created, and the floor is missing for all buildings. Although I did set `building_floor: true` in the config, and the point cloud contains all the point classes. I've tried several settings for these variables:

```yaml
lifting_options: 
  Building:
    height_roof: percentile-50
    height_floor: percentile-10
    triangulate: true

options:
  building_radius_vertex_elevation: 1.0
  radius_vertex_elevation: 0.5
  threshold_jump_edges: 0.25

buildings:
  horizontal_floor: false
  triangulated: true
```

The same configuration, but with CityGML output yield correct result (walls & floors included).

See my config and input for the OBJ: https://www.dropbox.com/s/2r6xkpp9e22esaa/3dfier_obj.zip?dl=0

![cloud](https://user-images.githubusercontent.com/7190603/31851726-d70b3a82-b66b-11e7-886a-27410f47611b.png)
![no-floor](https://user-images.githubusercontent.com/7190603/31851727-d72bf36c-b66b-11e7-909e-2b5a31b8aa22.png)
![no-walls](https://user-images.githubusercontent.com/7190603/31851728-d74ecf86-b66b-11e7-80da-17f0c74cd837.png)
