### ISSUE TITLE
Duplicate config options to triangulate buildings

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/3dfier#44]
I've just compiled from `master`. In the config file `myconfig.yml` the building triangulation can be set in two places, do they set the same parameter? If yes, i assume one overwrites the other?

```
lifting_options: 
  Building:
    triangulate: true

buildings:
  triangulated: false
```
