### ISSUE TITLE
many-outputs: CSV option is ambiguous

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/3dfier#62]
Tried:

```
$ 3dfier 25gn_many-outputs.yml --CSV 25gn.csv --CityGML 25gn.gml --PostGIS 25gn.sql
```

Got:

```
Error: option '--CSV' is ambiguous and matches '--CSV-BUILDINGS', '--CSV-BUILDINGS-ALL-Z', and '--CSV-BUILDINGS-MULTIPLE'
```

The config contains:

```
lifting_options: 
  Building:
    height_roof: percentile-90
    height_floor: percentile-10
    lod: 1

output: 
  building_floor: true
  vertical_exaggeration: 0

```
